### ISSUE TITLE
PipelineDB 1.0 support

### ISSUE THREAD

**Issue by jdbermeol** [pipelinedb/pipeline_kinesis#27]
Hello. Are you planning to support PipelineDB 1.0 in the near future? 

Thanks.

**Comment by derekjn** [comment]
@jdbermeol yes! `pipeline_kinesis` support for `1.0.0` will follow shortly after `pipeline_kafka`, which should be released at the end of this week.

Are you currently using `pipeline_kinesis`? If so, which version of PipelineDB are you running?

**Comment by jdbermeol** [comment]
Hi @derekjn Thanks for the fast reply. We are currently evaluating options so we don't have anything in production. Our current stream is using kinesis, and moving to Kafka is not in our priorities. I will start testing legacy PipelineDB binaries.

**Comment by derekjn** [comment]
@jdbermeol gotcha, that makes sense! One thing to consider here is simply writing your own Kinesis -> PipelineDB consumer.

Writes to PipelineDB streams are just regular [INSERT or COPY](http://docs.pipelinedb.com/streams.html#writing-to-streams) statements, and the `pipeline_kinesis` extension is basically just a really thin wrapper around that.

So your consumer would just connect to PipelineDB from the language of your choice (here are a few [examples](http://docs.pipelinedb.com/clients.html)) and generate `INSERT` or `COPY` statements appropriately based on the Kinesis messages being consumed. You can do this from any programming language that has a PostgreSQL library.

You'll likely be much better off using PipelineDB `1.0.0` with your own simple consumer that you can begin using right away. Having your own consumer will also give you a lot of flexibility so that it works just the right way for your workload, and will probably only be ~100 lines of code or so.

**Comment by jdbermeol** [comment]
@derekjn Thanks it works perfectly. I'm going to close this issue and wait for the native support. One final question or if you can point me to the documentation. Is it possible to do an intial batch load of data to the continuous views.

**Comment by derekjn** [comment]
> Is it possible to do an intial batch load of data to the continuous views.

@jdbermeol You can definitely [configure](http://docs.pipelinedb.com/conf.html) PipelineDB for backfilling. Here are some important parameters you can set to maximize throughput during initial loading:

```sh
# Defaults to 50ms, set it to something very high during batch loading (10s in this case)
pipelinedb.commit_interval = 10000

# Defaults to 10k, set it even higher during batch loading
pipelinedb.batch_size = 1000000

# Defaults to 50ms, set higher during batch loading (1s here)
pipelinedb.max_wait = 1000
```
Those should give you a pretty good throughput boost.

Furthermore, if you'd only like to target specific continuous queries (views/transforms) during backfilling, you can set [pipelinedb.stream_targets](http://docs.pipelinedb.com/streams.html?highlight=stream_targets#pipelinedb-stream-targets) so that only the specified continuous queries will read the backfilled events.
